language: node_js
node_js:
    - "4.2"
    - "5.0"

#os:
#    - linux
#    - osx

matrix:
    allow_failures:
#        - os: osx
#        - node_js: 5.0
    fast_finish: true

services:

addons:
  apt:
    packages:
      - clamav-freshclam
      - clamav-daemon
      - opendkim-tools
      - opendkim
      - spamassassin

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y opendkim
# - sudo test/install-spamassassin.sh
# - sudo test/install-clamav.sh

#before_script:
#script:

after_success:
  - npm install istanbul codecov.io
  - sudo test/install-spamassassin.sh
  - NODE_ENV=cov ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

#after_script:

sudo: required
