language: node_js
node_js:
    - "8"
    - "10"

#os:
#    - linux
#    - osx

matrix:
    allow_failures:
#        - os: osx
#        - node_js: "8"
    fast_finish: true

services:

addons:
  apt:
    packages:
      - clamav-freshclam
      - clamav-daemon
      - opendkim-tools
      - opendkim
      - spamassassin
      - dspam
      - rspamd

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y opendkim --force-yes
# - sudo apt-get install -y dspam --force-yes
# - sudo test/install-spamassassin.sh
# - sudo test/install-clamav.sh

#before_script:
#script:

after_success:
  - npm install istanbul codecov.io
  - sudo test/helpers/install-spamassassin.sh
  - sudo test/helpers/install-clamav.sh
  - sudo test/helpers/install-dspam.sh
# - sudo test/helpers/install-rspamd.sh  (not available on Ubuntu?)
  - NODE_ENV=cov ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

#after_script:

sudo: required
