language: node_js
node_js:
    - "0.10"
    - "4.2"

#os:
#    - linux
#    - osx

matrix:
    allow_failures:
#        - os: osx
#        - node_js: 4.2
    fast_finish: true

services:


before_script:

after_success:
    - npm run coverage
    - npm run coveralls

sudo: false
