language: node_js
node_js:
    - "4.2"
    - "5.0"

#os:
#    - linux
#    - osx

matrix:
    allow_failures:
#        - os: osx
#        - node_js: 5.0
    fast_finish: true

services:

addons:
  apt:
    packages:
      - clamav-freshclam
      - clamav-daemon
      - opendkim-tools
      - opendkim
      - spamassassin

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y opendkim
  - sudo apt-get install -y spamassassin
# - sudo apt-get install -y clamav clamav-base libclamav6 clamav-freshclam clamav-daemon
# freshclam takes 20+ minutes to download databases
# - sudo /usr/bin/freshclam
# - sudo /etc/init.d/clamav-daemon start

#before_script:
#script:

after_success:
# - npm run coverage
# - npm run coveralls
  - npm install istanbul
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec \
    && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

#after_script:

sudo: required
