name: Main workflow

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  run:
    name: Run
    strategy:
      matrix:
        node: [8, 10, 12]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm install

    - name: Lint
    - run: npm run lint

    - name: npm test
    - run: npm run test

services:
  redis:
    image: redis
    ports:
    - 6379/tcp